NUMBER_PATTERN = r'[+-]?[0-9]+[.]?[0-9]*[e]?[+-]?[0-9]*'
VECTOR_PATTERN = f'\\(\\s*({NUMBER_PATTERN})\\s+({NUMBER_PATTERN})\\s+({NUMBER_PATTERN})\\s*\\)\\s*'
FIELD_NAME_PATTERN = r'(\w+|\"\.\*\")\s+'
LIST_PATTERN = r'nonuniform\s+List<(scalar|vector)>\s*(\d+)\s*\(([^;]*)\)'
VALUE_PATTERN = f'(uniform)?\\s*(\\$?\\w*:*\\w*|{NUMBER_PATTERN}\\(?\\)?|{VECTOR_PATTERN})'
LIST_OR_VALUE_PATTERN = f'({VALUE_PATTERN}|{LIST_PATTERN})\\s*;'
BOUNDARY_FIELD_PATTERN = r'boundaryField\s+{\s+((.|\n)*)}'
BOUNDARY_BLOCK_PATTERN = f' *{FIELD_NAME_PATTERN}{{\\s+[^}}]*}}'
SPECIFIC_FIELD_PATTERN = r' *%s\s+{\s+[^}]*}'
SPECIFIC_FIELD_VALUES_PATTERN = r' *%s\s+{\s*([^}]*)}'
INTERNAL_FIELD_PATTERN = f'^\\s*internalField\\s+{LIST_OR_VALUE_PATTERN}'
SPECIAL_CHARACTERS = '"!@#$%^&*()-+?_=.,<>/'
SPECIFIC_VALUE_PATTERN = r' *%s\s+([^;]*);'
